[project]
name = "lnstxbridge"
requirements = []
costs_version = 1

[contracts.claim-for-trait]
path = "contracts/claim-for-trait.clar"
depends_on = []

[contracts.nft]
path = "contracts/nft.clar"
depends_on = ["nft-trait"]

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []

[contracts.sip10swap]
path = "contracts/sip10swap_v1.clar"
depends_on = []

[contracts.stxswap]
path = "contracts/stxswap_v9.clar"
depends_on = []

[contracts.triggerswap]
path = "contracts/triggerswap_v3.clar"
depends_on = ["sip-010-trait"]

[contracts.usda-token]
path = "contracts/usda-token.clar"
depends_on = ["sip-010-trait"]
