[project]
name = "lnstxbridge"
authors = []
description = ""
telemetry = false
requirements = []

[contracts.Wrapped-USD]
path = "contracts/Wrapped-USD.clar"
depends_on = ["restricted-token-trait", "sip-010-trait"]

[contracts.claim-for-trait]
path = "contracts/claim-for-trait.clar"
depends_on = []

[contracts.nft]
path = "contracts/nft.clar"
depends_on = ["nft-trait", "usda-token"]

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.restricted-token-trait]
path = "contracts/restricted-token-trait.clar"
depends_on = []

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []

[contracts.sip10swap]
path = "contracts/sip10swap_v3.clar"
depends_on = ["usda-token"]

[contracts.stxswap]
path = "contracts/stxswap_v10.clar"
depends_on = []

[contracts.triggerswap]
path = "contracts/triggerswap_v6.clar"
depends_on = ["sip-010-trait", "usda-token", "nft"]

[contracts.trustless-rewards]
path = "contracts/trustless-rewards.clar"
depends_on = []

[contracts.usda-token]
path = "contracts/usda-token.clar"
depends_on = ["sip-010-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
