[node]
working_dir = "/root/stacks-node/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = "0000000000000000000000000000000000000000000000000000000000000000"
local_peer_seed = "0000000000000000000000000000000000000000000000000000000000000000"
miner = true
mine_microblocks = true
microblock_frequency = 100
wait_time_for_microblocks = 0
use_test_genesis_chainstate = true
microblock_attempt_time_ms = 1_000

# https://github.com/stacks-network/stacks-blockchain/blob/7dc20797fb5d815ff4779063c0c0902443a44bb7/testnet/stacks-node/src/tests/neon_integrations.rs#L2811
#conf.node.mine_microblocks = true;
#conf.node.wait_time_for_microblocks = 1000;
#conf.node.microblock_frequency = 1000;
#conf.miner.microblock_attempt_time_ms = 120_000;
#conf.node.max_microblocks = 65536;
#conf.burnchain.max_rbf = 1000000;

#commit_anchor_block_within = 1_000_000
#mock_mining: false,
#mine_microblocks: true,
#microblock_frequency: 30_000,
#max_microblocks: u16::MAX as u64,
#wait_time_for_microblocks: 30_000,

[[events_observer]]
endpoint = "stacks-blockchain-api:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 120_000

[[ustx_balance]]
address = "ST3EQ88S02BXXD0T5ZVT3KW947CRMQ1C6DMQY8H19"
amount = 100000000000000

[[ustx_balance]]
address = "ST3KCNDSWZSFZCC6BE4VA9AXWXC9KEB16FBTRK36T"
amount = 100000000000000

[[ustx_balance]]
address = "ST30VXWG00R13WK8RDXBSTHXNWGNKCAQTRYEMA9FK"
amount = 100000000000000

[[ustx_balance]]
address = "ST27SD3H5TTZXPBFXHN1ZNMFJ3HNE2070QX7ZN4FF"
amount = 100000000000000

[[ustx_balance]]
address = "ST1N28QCRR03EW37S470PND4SPECCXQ22ZZHF97GP"
amount = 100000000000000