name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [14]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Global Dependencies
        run: npm -g install @stacks/cli

      - name: Install dependencies
        run: npm ci

      - name: Start containers
        run: npm run docker:regtest && npm run stacks:mocknet

      - name: Deploy Stacks contracts
        run: sleep 240 && npm run stacks:fund:old && sleep 30 && npm run stacks:deploy

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

      # - name: Integration tests - disabled for now
      #   run: npm run test:int
